/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railway.reservation.system;
import javax.swing.JOptionPane;
import java.io.*;
/**
 *
 * @author lenovo
 */
public class paymentmethod extends javax.swing.JFrame {

    /**
     * Creates new form paymentmethod
     */
    public paymentmethod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfield1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf7 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textfield1.setBackground(java.awt.Color.black);
        textfield1.setForeground(java.awt.Color.white);
        textfield1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Railway Reservation System Payment Method");
        textfield1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 530, 25));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("How would you like to pay?   1. Debit Card   2.  Credit Card");
        textfield1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 610, 24));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        textfield1.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 88, -1));

        label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label2.setText("Enter Card no: ");
        textfield1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 190, 180, -1));

        label3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label3.setText("Enter Expiry date:");
        textfield1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 280, 170, -1));

        label4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label4.setText("Enter Password: ");
        textfield1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 338, 160, -1));

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        textfield1.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 134, -1));
        textfield1.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 134, -1));
        textfield1.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 134, -1));

        label5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label5.setText("Credit Card");
        textfield1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 113, 100, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        textfield1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label1.setText("Debit Card");
        textfield1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 110, 20));

        label6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label6.setText("Enter Card no:");
        textfield1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 190, 140, -1));

        label7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label7.setText("Enter Expiry date:");
        textfield1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        label8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label8.setText("Enter Passowrd:");
        textfield1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 150, -1));
        textfield1.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 178, -1));
        textfield1.add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 178, -1));

        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        textfield1.add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 178, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        textfield1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 464, -1, -1));

        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        textfield1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/reservation/system/image2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        textfield1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textfield1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JOptionPane.showMessageDialog(this, "Transaction Successfull! Now please view your receipt. Thank You!");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        int a= Integer.parseInt(tf1.getText());
        if(a==1){
            JOptionPane.showMessageDialog(this, "You have selected Debit Card method for Payment ");
        }
        else if(a==2){
            JOptionPane.showMessageDialog(this, "You have selected Credit Card method for Payment ");
        }
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int i=JOptionPane.showConfirmDialog(null,"Are you sure you want to quit?", "Confirm",JOptionPane.YES_NO_OPTION);
       if(i==0){
           System.exit(0);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tf2.setText("");
        tf3.setText("");
        tf4.setText("");
        tf5.setText("");
        tf6.setText("");
        tf7.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentmethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentmethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentmethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentmethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentmethod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JPanel textfield1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JPasswordField tf7;
    // End of variables declaration//GEN-END:variables
}
